### ISSUE TITLE
Unsucccessful Installation

### ISSUE THREAD

**Issue by jkeilholz** [NASA-SW-VnV/fret#16]
Hello,

I seem to be having some recurring issues with trying to run an install of this application. Part of the problem appears to be deprecated dependencies and peer dependencies which need to be manually installed, but there is also a regular warning about a valid SPDX license expression. This is definitely not as straightforward nor as simple as running the four commands stated in the README. 

I've tried installing this on a Mac (10.15.6) as well as on a Linux system (Amazon Linux 2), both of which have a GUI client. I've not tried on a PC, but I'd also prefer not to install on that OS either. 

I have tried prior to the update regarding "npm run fret-install" as well as after. Neither works.

Can someone try to do a fresh install and possibly provide further details on what may be missing. I'm attaching the latest stdout from running "npm run fret-install"

[fret.log](https://github.com/NASA-SW-VnV/fret/files/5129545/fret.log)

**Comment by anmavrid** [comment]
Hello @jkeilholz,

Thanks for reporting this issue!

Could you please use the recommended node version v10.15.x for your installation? From your log file I see that you are using "node -v v14.8.0", which we do not support yet. For the re-installation please use the "npm run fret-reinstall" command (instead of "npm run fret-install").

**Comment by jkeilholz** [comment]
Hello @anmavrid,

Thank you very much for your response. Downgrading node to 10.15.x did the trick and it looks like we can move forward.

Best,
Joe
