### ISSUE TITLE
Variable Mapping Import

### ISSUE THREAD

**Issue by abakst** [NASA-SW-VnV/fret#34]
Hi,

I'd like to be able to specify the variable mappings for a project/component to accompany the exported requirements, so that a user can import both & check realizability themselves without providing the mappings. However, I can't quite figure out how to use the 'Import' feature in the 'Variable Mapping' pane of the Analysis Portal.

Thanks!

**Comment by anmavrid** [comment]
Hello Alexander,

The import feature of the Variables Mapping panel is used for importing model architectural information (e.g., Simulink input and output signals) in order to map these with the variables used in the FRET requirements. This allows users to generate specifications/monitors that can be automatically attached to the correct hierarchical level of the model for analysis.

However in your case you would like to be able to export the variable mappings from FRET once you have completed them and also export them together with the requirements of a specific FRET project, so then another FRET user can import them both and check realizability. 

Thats a great idea! We (the FRET team) have discussed about adding this, so we will try to make it available soon.

**Comment by abakst** [comment]
Cool!

**Comment by anmavrid** [comment]
We have added this in FRET v3.0! Instructions of how to import/export variables are written here: https://github.com/NASA-SW-VnV/fret/tree/master/fret-electron/docs/_media/user-interface/exportImport

I am closing this issue.

**Comment by kiniry** [comment]
Great; we look forward to taking it for a test drive!

**Comment by anmavrid** [comment]
Yay! We would love to receive your feedback.
