### ISSUE TITLE
Electron GPU initialization fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by Baltoli** [NASA-SW-VnV/fret#46]
This seems to be a common issue with `electron-builder`: https://github.com/Automattic/simplenote-electron/issues/3096. The error message I see is the same as listed in that issue.

I have been able to work around the problem by adding `--no-sandbox` to the `electron` invocation made by `npm start`.

**Comment by anmavrid** [comment]
Thanks for letting us know!

Anastasia

**Comment by Baltoli** [comment]
No problem; please let me know if I can supply any more information from my system.

**Comment by andreaskatis** [comment]
Hi @Baltoli,

Thank you again for bringing this to our attention! Would you mind trying `--in-process-gpu` instead of `--no-sandbox` , see if that works? I was looking into the issue earlier today and it seems like a preferrable workaround over disabling sandboxing.

We plan on adding a relevant note about it in our installation guide with our next release.

Best Regards,

Andreas

**Comment by Baltoli** [comment]
If I use the `--in-process-gpu` flag, I see the same startup messages in the console I've launched FRET from as I do with `--no-sandbox`, but the electron shell doesn't appear.

**Comment by andreaskatis** [comment]
Thank you, @Baltoli !

**Comment by anmavrid** [comment]
I am closing this issue. We have added a note in the FRET installation instructions that will appear in the next release.

Thanks everyone.

Anastasia

**Comment by 1thorsheikh0** [comment]
hey team, i am facing a problem of just a white screen for even half an hour and found nothing like the FRET interface in the screen shots. plz guide me

**Comment by andreaskatis** [comment]
Hi @1thorsheikh0,

Thanks for reaching out. Can you clarify on whether you have tried running the app using 

```
npm start --no-sandbox
```

If yes, can you provide us with more information regarding the environment that you are trying to run FRET in? More specifically, the operating system, its version and the versions of NodeJS and Python that you have installed.

Best,

Andreas

**Comment by 1thorsheikh0** [comment]
Tnx for your response.
I have WSL2 environment with NodeJs and Python installed as mentioned in
your Respositry instructions.
I have cloned the FRET and installed the "npm" Command.
But when i give command " Npm start ", the fret opens with clear white
screen and nothing renders.
Pl guide me

**Comment by andreaskatis** [comment]
Hi @1thorsheikh0 ,

Thanks for providing additional information.

1. Please provide a screenshot or a text copy of the terminal window from which you run FRET, after you see the white screen. Sometimes the terminal's output is useful for determining the source of the issue.
2.  Could you please confirm that the white screen occurs when using `npm start --no-sandbox`, instead of `npm start`? It was not clear from your response whether this is the case.
3. Apart from NodeJS and Python, have you installed the rest of the required dependencies? This includes the following:

    - `gcc`, `g++`, `make`
    - `libgtk-3-0t64 libdrm2 libgbm1 libnss3 libx11-xcb1 libasound2t64` for Ubuntu 24.04 or later , or `libgtk-3.0 libdrm2 libgbm1 libnss3 libx11-xcb1 libasound2` for older versions.
4. Finally, can you provide information regarding the version of NodeJS (by running `node --version`) and Python (by running `python3 --version`)?

Best,

Andreas

**Comment by 1thorsheikh0** [comment]
sir,
I am very thankful to you for this act of kindness.
I am sharing some of the screenshots from my " WSL2 Command Prompt" so that
you understand what kind of environment i used.
second, I am pasting an error that i face after the successful installation
of NPM dependencies.
*Error:*  A JavaScript error occurred in the main process Uncaught
Exception:
/home/book_15_5/fret/fret-electron/app/index.js:6 import React from
'react'; ^^^^^^ SyntaxError:
Cannot use import statement outside a module at internalCompileFunction
(node:internal/vm:73:18) at wrapSafe
(node:internal/modules/cjs/loader:1185:20) at Module._compile
(node:internal/modules/cjs/loader:1227:27) at Object..js
(node:internal/modules/cjs/loader:1326:10) at Module.load
(node:internal/modules/cjs/loader:1126:32) at
node:internal/modules/cjs/loader:967:12 at Function._load
(node:electron/js2c/node_init:2:13357) at loadApplicationPackage
(/home/book_15_5/fret/fret-electron/node_modules/electron/dist/resources/default_app.asar/main.js:121:16)
at Object.<anonymous>
(/home/book_15_5/fret/fret-electron/node_modules/electron/dist/resources/default_app.asar/main.js:233:9)
at Module._compile (node:internal/modules/cjs/loader:1271:14)

**Comment by 1thorsheikh0** [comment]
hey sir,
now I
 have just the rendering problem, that the real interface of the fret is
not showing properly

**Comment by andreaskatis** [comment]
Hi @1thorsheikh0 ,

We still need more information to help you with the issue. Can you please go through the steps 2-4 that I had listed in my previous response and provide an answer for each?
