### ISSUE TITLE
could not install fret

### ISSUE THREAD

**Issue by aogrcs** [NASA-SW-VnV/fret#47]
### Dear,
I install fret under ubuntu 20.04, node version is 16.11.0, npm version is 8.0.0, nusmv version is 2.6.0, I follow the instruction but get errors as following:
npm ERR! code 1
npm ERR! path /home/cocosim/fret/fret-electron/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: connect ECONNREFUSED 223.75.236.241:443
npm ERR!     at ClientRequest.<anonymous> (/home/cocosim/fret/fret-electron/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:510:26)
npm ERR!     at ClientRequest.emit (node:events:402:35)
npm ERR!     at ClientRequest.origin.emit (/home/cocosim/fret/fret-electron/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketErrorListener (node:_http_client:447:9)
npm ERR!     at TLSSocket.emit (node:events:390:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cocosim/.npm/_logs/2023-01-12T02_51_02_716Z-debug.log

**Comment by andreaskatis** [comment]
Hi @aogrcs,

Looking at the log, it seems like an issue related to your network settings. It seems like your system configuration prevents connections related to the installation script.

It may be useful to manually run the offending command `sh - c node install.js` under 'fret/fret-electron/node_modules/electron', and see if you get any further details that could help you.

Best Regards,

Andreas

**Comment by aogrcs** [comment]
Dear @andreaskatis I could find this fold

**Comment by andreaskatis** [comment]
@aogrcs Did you mean to say that you cannot find the folder? That probably means that it is temporarily created during the installation and automatically deleted after it ends/fails.

Regardless, the error message that you are seeing has to do with the system not being able to connect to a remote repository/server that is necessary for that step of the installation process.

Please make sure that the system has a stable internet connection. If it does, then the issue is most probably related to firewall settings that prevent access to specific servers/repositories.

Best Regards,

Andreas

**Comment by aogrcs** [comment]
Dear @andreaskatis Yes, it related to firewall settings even I use client, but this command solve it
npm config set ELECTRON_MIRROR http://npm.taobao.org/mirrors/electron/
thanks

**Comment by andreaskatis** [comment]
Good to know there's a workaround! Thanks for letting us know!
