### ISSUE TITLE
Unable to run executable built with Docker on Ubuntu 22.04

### ISSUE THREAD

**Issue by Dav-11** [NASA-SW-VnV/fret#61]
Hi,
I am having trouble with installing FRET on Ubuntu desktop (both 22.04 and 23.10).

If I try to install it with the node method (using node 16.16)
> Here are the steps to install and start FRET:
> 1. cd fret-electron
> 2. npm run fret-install (please do 'npm run fret-reinstall' instead if you already have a FRET installation)
> 3. npm start

It does work, but if I try to use the docker method, it generates the executable successfully, but when I try to run it this error shows:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module "../../analysis/connected_components"
    at /home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:1546319
    at Object../model/realizabilitySupport/realizabilityUtils.js (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:1546423)
    at t (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:124)
    at Object../model/FretModel.js (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:1508006)
    at t (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:124)
    at Object../app/main.dev.js (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:692)
    at t (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:124)
    at module.exports../app/main.dev.js (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:472)
    at Object.<anonymous> (/home/user/Desktop/fret-desktop/FRET-linux-x64/resources/app/main.prod.js:1:499)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

**Comment by andreaskatis** [comment]
Hello @Dav-11 ,

Thank you for trying out FRET! This issue has already been fixed in our internal repository. The fix will be part of our next public release.

In the meantime, if you want to try the built executable using the Docker image, you can apply the attached patch to your clone repository. To do so, follow the steps below.

1. Download this patch file to a location of your choice: [dockerFix.patch](https://github.com/NASA-SW-VnV/fret/files/13209981/dockerFix.patch)
2. Change directory to the fret repository `cd /path/to/fret`
3. Apply the patch: `git am --3way --ignore-space-change ~/git/fret/fret-electron/dockerFix.patch`

After the patch has been applied, follow the (updated) guide below.

1. `cd fret` (**You most probably don't need this if you follow these steps immediately after applying tha patch**)
2. `mv tools/Scripts/docker/Dockerfile .`
3. `mv tools/Scripts/docker/generate_executable_Linux.sh .`
4. `docker build -t fret-install -f Dockerfile .`
5. `mkdir ../fret-desktop (Replace path with your preference)`
6. `docker run -v $PWD/../fret-desktop:/tmp/fret -u root -it fret-install:latest /bin/bash`
7. `cp ~fret/Desktop/FRET-linux-x64.tgz /tmp/fret/`
8. `exit` (to exit the docker image)
9. `cd ../fret-desktop`
10. `tar -xzvf FRET-linux-x64.tgz`
11. `cd FRET-linux-x64`
12. `./FRET` (or `./FRET --no-sandbox` if the application doesn't load)

Please keep in mind that the following note in our instructions may still be relevant:

If you encounter glibc-related issues when using the executable built by the Docker image, try the following steps:
1. Open the "Dockerfile" file in an editor (this file should be in the "fret" root folder if you already attempted to build a binary)
2. Change "FROM ubuntu:latest" to "FROM ubuntu:focal"
3. Try again the Docker instructions, starting with step 4.

Best Regards,

Andreas

**Comment by Dav-11** [comment]
Thank You very much, 
with the fix it worked flawlessly.
