### ISSUE TITLE
pmLTL and fmLTL don't seem to be equivalent

### ISSUE THREAD

**Issue by SoftPro** [NASA-SW-VnV/fret#79]
Hi，

When I used the FRET tool to simulate the protocol run, I found that the PmLTL execution results were different from the FmLTL execution results.

For the following FRETish Requirement: in m1 when i1 the system shall at the next timepoint satisfy o1. The execution trace of pmltl is as follows: 
![image](https://github.com/NASA-SW-VnV/fret/assets/89380949/6725de83-0227-4f42-b588-e3de25cd70d6)

Fmltl execution trace is as follows:
![image](https://github.com/NASA-SW-VnV/fret/assets/89380949/ea12751e-6d6e-424e-a522-fe46688e5ced)

Follow A Compositional Proof Framework for FRETish  Requirements paper, it seems that only pmltl conforms to the trigger function. I'm not sure and would like to ask this question.

Yours Frankly,
SoftPro

**Comment by tpressburger** [comment]
We expect the color of the trace representing the requirement's satisfaction to be the same for past time and future time, which your traces show it is. We don't expect the traces to be identical because they are evaluating the requirement over different traces. There is a section called Visualization in the simulator documentation:

Visualization
When visualizing the future-time formalization, the bottom trace shows, at each timepoint, the evaluation of the formula on the trace starting at that timepoint and extending to the end of the trace. For example, with a tracelength of 40, the formula is evaluated forwards starting from timepoint 0 to the end of the trace (timepoint 39), from timepoint 1 to the end of the trace, etc. The overall color is the evaluation at timepoint 0. When visualizing the past-time formalization, the bottom trace shows, at each timepoint, the evaluation of the trace starting at timepoint 0 and extending to the timepoint. For example, the formula is evaluated at timepoint 39 for the trace from timepoint 0 to timepoint 39, at timepoint 38 for the trace from timepoint 0 to timepoint 38, etc. The overall color is the evaluation at timepoint 39.

So in your example, the future-time trace shows that the trace from 12 to 39 does not satisfy the requirement, because o1 is not true at time point 13. The past time trace shows that the trace from 12 to 0 satisfies the trace because indeed o1 is is true at point 12.

**Comment by SoftPro** [comment]
Hi，tpressburger
     Thank you for your answer. I understand what you mean now. 
Yours Frankly,
SoftPro

**Comment by anmavrid** [comment]
Thanks. I am closing this issue.
